### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by Git-Hoon** [wgPython/video_spider#3]
你好，我正在腾讯视频网站某部电影观影页（https://v.qq.com/x/cover/mzc002000149ian.html），将目标url设置为这个网站url后，解析结果为什么还是你初始那篇文章中的视频？

**Comment by wxy2077** [comment]
额， 这个貌似下载不了这样的电影之类的，我当初研究这个是针对微信文章网页内的腾讯视频。
